environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35-x64
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"


build: false


install:
  - git submodule update --init --recursive
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -v -n test-environment -c conda-forge python=%PYTHON_VERSION% "numpy>=1.13" scipy pyqt matplotlib pyopengl h5py numexpr astropy tornado cython pandas runipy cython pytest numba "pyarrow>=0.12" graphviz python-graphviz pcre"
  - activate test-environment
  - pip install -r requirements.txt
  - pushd packages\vaex-core   && pip install . && popd
  - pushd packages\vaex-hdf5   && pip install . && popd
  - pushd packages\vaex-arrow   && pip install . && popd
  - pushd packages\vaex-viz   && pip install . && popd
  - pushd packages\vaex-server   && pip install . && popd
  - pushd packages\vaex-astro   && pip install . && popd
  - pushd packages\vaex-distributed   && pip install . && popd
  - pushd packages\vaex-jupyter   && pip install . && popd
  - pushd packages\vaex-ui   && pip install . && popd

test_script:
 - python -m vaex.test.dataset TestDataset
 - py.test tests/
# - runipy examples/tutorial_ipython_notebook.ipynb
# - runipy examples/advanced_plotting.ipynb
